qerror: add five qerror strings
RH-Author: Amos Kong <akong@redhat.com>
Message-id: <1349100767-9066-4-git-send-email-akong@redhat.com>
Patchwork-id: 42562
O-Subject: [RHEL-6.4 qemu-kvm PATCH v7 03/14] qerror: add five qerror strings
Bugzilla: 680356
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Markus Armbruster <armbru@redhat.com>
RH-Acked-by: Orit Wasserman <owasserm@redhat.com>

Add five new qerror strings, they are about listen/connect socket:
  QERR_SOCKET_CONNECT_IN_PROGRESS
  QERR_SOCKET_CONNECT_FAILED
  QERR_SOCKET_LISTEN_FAILED
  QERR_SOCKET_BIND_FAILED
  QERR_SOCKET_CREATE_FAILED

(Cherry-picked from commit aed3d11df6d14ce63ac754601e4df965c608f6bd)

Conflicts:
    qerror.h

Reviewed-by: Michael Roth <mdroth@linux.vnet.ibm.com>
Signed-off-by: Amos Kong <akong@redhat.com>
Reviewed-by: Orit Wasserman <owasserm@redhat.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>
---
 qerror.c |   20 ++++++++++++++++++++
 qerror.h |   15 +++++++++++++++
 2 files changed, 35 insertions(+), 0 deletions(-)

Signed-off-by: Michal Novotny <minovotn@redhat.com>