Force newer spice-protocol.
Otherwise qemu build breaks with many errors like:

/home/rjones/d/fedora/qemu/master/qemu-kvm-0.15.0/hw/qxl.c:131:26: error: 'QXL_INTERRUPT_ERROR' undeclared (first use in this function)
/home/rjones/d/fedora/qemu/master/qemu-kvm-0.15.0/hw/qxl.c:131:26: note: each undeclared identifier is reported only once for each function it appears in
/home/rjones/d/fedora/qemu/master/qemu-kvm-0.15.0/hw/qxl.c: In function 'io_port_to_string':
/home/rjones/d/fedora/qemu/master/qemu-kvm-0.15.0/hw/qxl.c:495:10: error: 'QXL_IO_UPDATE_AREA_ASYNC' undeclared (first use in this function)

We also force newer spice-server-devel for good measure.