qerror: OpenFileFailed: add __com.redhat_error_message key
RH-Author: Luiz Capitulino <lcapitulino@redhat.com>
Message-id: <1349979864-509-2-git-send-email-lcapitulino@redhat.com>
Patchwork-id: 42992
O-Subject: [RHEL6.4 qemu-kvm PATCH 1/6] qerror: OpenFileFailed: add __com.redhat_error_message key
Bugzilla: 806775
RH-Acked-by: Laszlo Ersek <lersek@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Pavel Hrdina <phrdina@redhat.com>

It's a string that will be used by callers to pass the error message
returned by strerror().

Right now callers pass "", as qerror doesn't support passing NULL.
Next commits will convert them to pass the real error message.

Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
---
 blockdev.c           | 10 +++++-----
 dump.c               |  2 +-
 monitor.c            |  4 ++--
 qerror.c             |  2 +-
 qerror.h             |  2 +-
 qga/commands-posix.c |  2 +-
 6 files changed, 11 insertions(+), 11 deletions(-)

Signed-off-by: Michal Novotny <minovotn@redhat.com>