Suppress prototype warning for nss headers
RH-Author: Miroslav Rezanina <mrezanin@redhat.com>
Message-id: <20201203111702.215084-1-mrezanin@redhat.com>
Patchwork-id: 100201
O-Subject: [RHEL-7.9.z qemu-kvm PATCH] Suppress prototype warning for nss headers
Bugzilla: 1884997
RH-Acked-by: Thomas Huth <thuth@redhat.com>
RH-Acked-by: Stefan Hajnoczi <stefanha@redhat.com>
RH-Acked-by: Jon Maloy <jmaloy@redhat.com>

From: Miroslav Rezanina <mrezanin@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1884997
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33460150
branch: rhel79/master
Upstream: n/a

Rebase of nss introduced following warning when using it for building qemu-kvm:

/usr/include/nss3/pk11pub.h:951:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
int SECMOD_GetSystemFIPSEnabled();

This issue is tracked by https://bugzilla.redhat.com/show_bug.cgi?id=1885321. However,
this issue is not important enough to fix (as discussed in the bugzilla).

We have to hack qemu-kvm to live with this warning. To do it we add following hacks:

1) We disable using -Werror for nss test in configure. This allows configure to pass.

2) We disable -Werror=scrict-prototypes when including nss headers. This allows build to pass.

Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>
Signed-off-by: Jon Maloy <jmaloy.redhat.com>