Fix compilation error (missing include statement)
RH-Author: Christoph Hellwig <chellwig@redhat.com>
Message-id: <1289325254-25070-6-git-send-email-chellwig@redhat.com>
Patchwork-id: 13357
O-Subject: [RHEL6.1 qemu PATCH 1/5] Fix compilation error (missing include
	statement)
Bugzilla: 608548
RH-Acked-by: Eduardo Habkost <ehabkost@redhat.com>
RH-Acked-by: Avi Kivity <avi@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>

From: Stefan Weil <weil@mail.berlios.de>

./hw/sd.c: In function ‘sd_init’:
./hw/sd.c:443: error: implicit declaration of function ‘qemu_blockalign’
./hw/sd.c:443: error: nested extern declaration of ‘qemu_blockalign’
./hw/sd.c:443: error: assignment makes pointer from integer without a cast

Cc: Christoph Hellwig <hch@lst.de>
Cc: Kevin Wolf <kwolf@redhat.com>
Signed-off-by: Stefan Weil <weil@mail.berlios.de>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>
Upstream commit: 879f0655579a1f94fab2cd20a1597aef9a3117ef
BZ: 608548

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>