qerror: Add QERR_UNKNOWN_BLOCK_FORMAT_FEATURE
RH-Author: Kevin Wolf <kwolf@redhat.com>
Message-id: <1300283560-13085-7-git-send-email-kwolf@redhat.com>
Patchwork-id: 20136
O-Subject: [RHEL-6.1 qemu-kvm PATCH 6/8] qerror: Add
	QERR_UNKNOWN_BLOCK_FORMAT_FEATURE
Bugzilla: 688119
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Jes Sorensen <Jes.Sorensen@redhat.com>
RH-Acked-by: Markus Armbruster <armbru@redhat.com>

Bugzilla: 688119

Signed-off-by: Kevin Wolf <kwolf@redhat.com>
Reviewed-by: Anthony Liguori <aliguori@us.ibm.com>
(cherry picked from commit f54e3641122e51c6343d587805422642f307462e)
---
 qerror.c |    5 +++++
 qerror.h |    3 +++
 2 files changed, 8 insertions(+), 0 deletions(-)

Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>