error: drop error_get_qobject()/error_set_qobject()
RH-Author: Laszlo Ersek <lersek@redhat.com>
Message-id: <1367868499-27603-6-git-send-email-lersek@redhat.com>
Patchwork-id: 51104
O-Subject: [RHEL-6.5 qemu-kvm PATCH v2 05/56] error: drop error_get_qobject()/error_set_qobject()
Bugzilla: 952873
RH-Acked-by: Jeffrey Cody <jcody@redhat.com>
RH-Acked-by: Gerd Hoffmann <kraxel@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>

error_get_qobject() is unused since last commit, error_set_qobject()
has never been used. Also drops error_int.h.

Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
Reviewed-by: Markus Armbruster <armbru@redhat.com>
(cherry picked from commit 7795b166d9d1e2b33d428f5acab6d0d5e617ee91)

Conflicts:

	error.c
	error_int.h

RHEL-6 notes:
- "qapi/qmp-dispatch.c" continues to call error_get_data(), which is
  implemented in "error.c",
- "last commit" corresponds to 23576911332d7b2f40b633467c74d338af0f0c99 in
  RHEL-6.

Signed-off-by: Laszlo Ersek <lersek@redhat.com>
---
 v2: resolved "last commit" for RHEL-6.

 error_int.h |    2 --
 error.c     |   19 -------------------
 qemu-ga.c   |    1 -
 3 files changed, 0 insertions(+), 22 deletions(-)

Signed-off-by: Michal Novotny <minovotn@redhat.com>