Bugzilla: 856851 Brew: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=4860099 Upstream: internal issue Test: tested in localhost
'make rh-rpms' doesn't work, error was introduced by commit e1e5e2f3

cc1: warnings being treated as errors
/qemu/redhat/rpm/BUILD/qemu-kvm-0.12.1.2/hw/acpi.c: In function
‘piix4_pm_init’:
/qemu/redhat/rpm/BUILD/qemu-kvm-0.12.1.2/hw/acpi.c:754: error:
implicit declaration of function ‘fw_cfg_add_file’

Signed-off-by: Amos Kong <akong@redhat.com>