QError: Introduce QERR_QMP_EXTRA_MEMBER
Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
(cherry picked from commit 60d76d7b073f6f25c9dbe4d68df7d012f73db27f)

Conflicts:

	qerror.c
	qerror.h
Signed-off-by: Jeff Cody <jcody@redhat.com>