util: Improve os_mem_prealloc error message
Message-id: <20141104132608.310567a7@redhat.com>
Patchwork-id: 62082
O-Subject: [RHEL7.1 qemu-kvm-rhev PATCH] util: Improve os_mem_prealloc error message
Bugzilla: 1153590
RH-Acked-by: Andrew Jones <drjones@redhat.com>
RH-Acked-by: Amos Kong <amos@redhat.com>
RH-Acked-by: Dr. David Alan Gilbert (git) <dgilbert@redhat.com>

Currently, when the preallocating guest memory process fails, a not
so helpful error message is printed out:

    # virsh start migt10
    error: Failed to start domain migt10
    error: internal error: process exited while connecting to monitor:
    os_mem_prealloc: failed to preallocate pages

>From the error message it's not clear at the first glance where the
problem lies. However, changing the error message might give users a
clue.

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>
Reviewed-by: Eric Blake <eblake@redhat.com>
Signed-off-by: Michael Tokarev <mjt@tls.msk.ru>
(cherry picked from commit 404ac83efd5761c6b590fd9f00fbbe8ee2281aa6)
Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>