configure: duplicate/incorrect order of -lrt
RH-Author: John Snow <jsnow@redhat.com>
Message-id: <1428345980-16249-5-git-send-email-jsnow@redhat.com>
Patchwork-id: 64720
O-Subject: [RHEL-6.7 qemu-kvm PATCH 4/5] configure: duplicate/incorrect order of -lrt
Bugzilla: 1208605
RH-Acked-by: Fam Zheng <famz@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Bandan Das <bsd@redhat.com>

From: Rick Liu <yrliu.ca@gmail.com>

'-lrt' flag duplication/incorrect order
would cause 'undefined reference to clock_gettime' error during compilation time.

Before fix:
... -o qemu-bridge-helper qemu-bridge-helper.o    -lrt -pthread -lgthread-2.0 -lrt -lglib-2.0
After fix:
... -o qemu-bridge-helper qemu-bridge-helper.o    -pthread -lgthread-2.0 -lrt -lglib-2.0

Reference:
http://hi.baidu.com/sanitywolf/item/7a8b69c1e76dd220a0b50ab1

Signed-off-by: Rick Liu <yrliu.ca@gmail.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 18e588b197545412cad65f0b07e13c161cac4bea)
Signed-off-by: John Snow <jsnow@redhat.com>
---
 configure | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

Signed-off-by: Jeff E. Nelson <jen@redhat.com>