error: add error_setg_file_open() helper
RH-Author: Gerd Hoffmann <kraxel@redhat.com>
Message-id: <1381757723-23134-6-git-send-email-kraxel@redhat.com>
Patchwork-id: 54853
O-Subject: [RHEL-7 qemu-kvm PATCH 05/15] error: add error_setg_file_open() helper
Bugzilla: 922010
RH-Acked-by: Hans de Goede <hdegoede@redhat.com>
RH-Acked-by: Laszlo Ersek <lersek@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>

From: Luiz Capitulino <lcapitulino@redhat.com>

Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
Acked-by: Kevin Wolf <kwolf@redhat.com>
(cherry picked from commit 54028d7542cffe97c4685994baac66988c4b7db9)
---
 include/qapi/error.h | 5 +++++
 util/error.c         | 5 +++++
 2 files changed, 10 insertions(+)

Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>