build: reenable local builds to pass --enable-debug (downstream only)
Message-id: <1423650356-15453-2-git-send-email-lersek@redhat.com>
Patchwork-id: 63795
O-Subject: [RHEV-7.2 qemu-kvm-rhev PATCH 1/1] build: reenable local builds to pass --enable-debug (downstream only)
Bugzilla:
RH-Acked-by: Wei Huang <wei@redhat.com>
RH-Acked-by: Markus Armbruster <armbru@redhat.com>
RH-Acked-by: Miroslav Rezanina <mrezanin@redhat.com>

qemu-kvm-rhev commit 58d7b7a8 dropped the "isa-ide" device for x86_64. It
observed:

  Unresolved extern symbols pose no real danger, because they fail safely
  at link time.  Note for the curious: the optimizer gets rid of the
  reference to isa_ide_init() in hw/i386/pc_piix.c.

For local builds it is sometimes useful to pass --enable-debug to the
configure script. However that flag disables the optimizer, and the
isa_ide_init() call is not eliminated during compilation; it reaches the
linker. The linker then barfs

    LINK  x86_64-softmmu/qemu-system-x86_64
  hw/i386/pc_piix.o: In function `pc_init1':
  .../hw/i386/pc_piix.c:252: undefined reference to `isa_ide_init'
  collect2: error: ld returned 1 exit status

Provide a stub implementation for isa_ide_init(), reenabling local debug
builds.

No copyright notice is added to the top of the new file, following the
pattern set by other stub files.

Signed-off-by: Laszlo Ersek <lersek@redhat.com>
---
 stubs/Makefile.objs |  1 +
 stubs/ide-isa.c     | 12 ++++++++++++
 2 files changed, 13 insertions(+)
 create mode 100644 stubs/ide-isa.c

Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>