exec: Fix prototype of phys_mem_set_alloc and related functions
RH-Author: Michael S. Tsirkin <mst@redhat.com>
Message-id: <1387293161-4085-57-git-send-email-mst@redhat.com>
Patchwork-id: 56362
O-Subject: [PATCH qemu-kvm RHEL7.0 v2 56/57] exec: Fix prototype of phys_mem_set_alloc and related functions
Bugzilla: 1034876
RH-Acked-by: Igor Mammedov <imammedo@redhat.com>
RH-Acked-by: Marcel Apfelbaum <marcel.a@redhat.com>
RH-Acked-by: Laszlo Ersek <lersek@redhat.com>
RH-Acked-by: Orit Wasserman <owasserm@redhat.com>

From: Stefan Weil <sw@weilnetz.de>

phys_mem_alloc and its assigned values qemu_anon_ram_alloc and
legacy_s390_alloc must have identical argument lists.

legacy_s390_alloc uses the size parameter to call mmap, so size_t is
good enough for all of them.

This patch fixes compiler errors on i686 Linux hosts:

  CC    alpha-softmmu/exec.o
exec.c:752:51: error:
 initialization from incompatible pointer type [-Werror]
exec.c: In function 'qemu_ram_alloc_from_ptr':
exec.c:1139:32: error:
 comparison of distinct pointer types lacks a cast [-Werror]
exec.c: In function 'qemu_ram_remap':
exec.c:1283:21: error:
 comparison of distinct pointer types lacks a cast [-Werror]

Signed-off-by: Stefan Weil <sw@weilnetz.de>
Reviewed-by: Markus Armbruster <armbru@redhat.com>
Message-id: 1380481005-32399-1-git-send-email-sw@weilnetz.de
Signed-off-by: Anthony Liguori <aliguori@amazon.com>
(cherry picked from commit 575ddeb459f622a114cbfe37d220c0519ec9c2a4)

Note: not directly related to this change, and we don't have
to support building on i686.
However this is gratitious and ugly difference from upstream,
and some machines I use to test ACPI are i686, so including
this here was required for testing.
---
 include/exec/exec-all.h | 2 +-
 exec.c                  | 4 ++--
 target-s390x/kvm.c      | 4 ++--
 3 files changed, 5 insertions(+), 5 deletions(-)

Signed-off-by: Michal Novotny <minovotn@redhat.com>