io: Add missing GCC_FMT_ATTR (fix -Werror=suggest-attribute=format)
RH-Author: Daniel P. Berrange <berrange@redhat.com>
Message-id: <20171220175702.29663-21-berrange@redhat.com>
Patchwork-id: 78473
O-Subject: [RHV-7.5 qemu-kvm-rhev PATCH v2 20/20] io: Add missing GCC_FMT_ATTR (fix -Werror=suggest-attribute=format)
Bugzilla: 1518649
RH-Acked-by: John Snow <jsnow@redhat.com>
RH-Acked-by: Jeffrey Cody <jcody@redhat.com>
RH-Acked-by: Miroslav Rezanina <mrezanin@redhat.com>

From: Stefan Weil <sw@weilnetz.de>

This fixes a compiler warning:

/qemu/io/channel-websock.c:163:5: error:
 function might be possible candidate for ‘gnu_printf’ format attribute
 [-Werror=suggest-attribute=format]

Signed-off-by: Stefan Weil <sw@weilnetz.de>
Acked-by: Daniel P. Berrange <berrange@redhat.com>
Signed-off-by: Michael Tokarev <mjt@tls.msk.ru>
(cherry picked from commit 52aa5644e8e89ebfc3b1d0abdb7cc502ce9db599)
Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>