QError: Introduce qerror_format()
Will be used by new error propagation framework to convert Error objects
into human-readable form.

Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
Signed-off-by: Michael Roth <mdroth@linux.vnet.ibm.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>
(cherry picked from commit 87c2f59166b7ec5b3ce44b5c4a2337c07a78e533)

Conflicts:

	qerror.h
Signed-off-by: Jeff Cody <jcody@redhat.com>