qerror: add QERR_INVALID_PARAMETER_COMBINATION
RH-Author: Jeffrey Cody <jcody@redhat.com>
Message-id: <f1bd760f15c46ed31b37d7f809987b219bfa2ba4.1350447475.git.jcody@redhat.com>
Patchwork-id: 43287
O-Subject: [RHEL6.4 qemu-kvm PATCH v4 29/35] qerror: add QERR_INVALID_PARAMETER_COMBINATION
Bugzilla: 767233
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Eric Blake <eblake@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>

This error was introduced in upstream commit 727f005.  Rather than
backport that entire commit, this patch simply adds that error type.

Signed-off-by: Jeff Cody <jcody@redhat.com>
---
 qerror.c | 4 ++++
 qerror.h | 3 +++
 2 files changed, 7 insertions(+)

Signed-off-by: Michal Novotny <minovotn@redhat.com>