qerror: drop QERR_OPEN_FILE_FAILED macro
RH-Author: Laszlo Ersek <lersek@redhat.com>
Message-id: <1383236971-6067-9-git-send-email-lersek@redhat.com>
Patchwork-id: 55198
O-Subject: [RHEL-7 qemu-kvm PATCH 8/8] qerror: drop QERR_OPEN_FILE_FAILED macro
Bugzilla: 907743
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>

From: Luiz Capitulino <lcapitulino@redhat.com>

Not used since the last commit.

Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
Acked-by: Kevin Wolf <kwolf@redhat.com>
(cherry picked from commit dbfbc6373441e436ac6e2bcf7a8acb284225aa21)
Signed-off-by: Laszlo Ersek <lersek@redhat.com>
---
 include/qapi/qmp/qerror.h | 3 ---
 1 file changed, 3 deletions(-)

Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>