dump: add APIs to operate DataCache
RH-Author: Laszlo Ersek <lersek@redhat.com>
Message-id: <1395459071-19118-16-git-send-email-lersek@redhat.com>
Patchwork-id: 58226
O-Subject: [RHEL-6.6 qemu-kvm PATCH 15/19] dump: add APIs to operate DataCache
Bugzilla: 1035162
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Dr. David Alan Gilbert (git) <dgilbert@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

From: qiaonuohan <qiaonuohan@cn.fujitsu.com>

DataCache is used to store data temporarily, then the data will be written to
vmcore. These functions will be called later when writing data of page to
vmcore.

Signed-off-by: Qiao Nuohan <qiaonuohan@cn.fujitsu.com>
Reviewed-by: Laszlo Ersek <lersek@redhat.com>
Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
(cherry picked from commit 64cfba6a47411092c941c8d17256fb5673cc8cbf)

Conflicts:
	dump.h

RHEL-6 note: DataCache.offset is of type "off_t"; I'm including <sys/types.h>
in dump.h as a downstream mesure against

In file included from cpu-all.h:25,
                 from target-i386/cpu.h:1003,
                 from target-i386/exec.h:66,
                 from cpu-exec.c:20:
dump.h:151: error: expected specifier-qualifier-list before 'off_t'

Signed-off-by: Laszlo Ersek <lersek@redhat.com>
---
 dump.h | 11 +++++++++++
 dump.c | 47 +++++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 58 insertions(+)

Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>