qcow2-refcount: remove write-only variables
RH-Author: Kevin Wolf <kwolf@redhat.com>
Message-id: <1329218101-24213-35-git-send-email-kwolf@redhat.com>
Patchwork-id: 37224
O-Subject: [RHEL-6.3 qemu-kvm PATCH v2 34/96] qcow2-refcount: remove write-only variables
Bugzilla: 783950
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Marcelo Tosatti <mtosatti@redhat.com>
RH-Acked-by: Laszlo Ersek <lersek@redhat.com>

From: Blue Swirl <blauwirbel@gmail.com>

Bugzilla: 783950

Variables l2_modified and l2_size are not really used, remove them.
Spotted by GCC 4.6.0:
  CC    block/qcow2-refcount.o
/src/qemu/block/qcow2-refcount.c: In function 'qcow2_update_snapshot_refcount':
/src/qemu/block/qcow2-refcount.c:708:37: error: variable 'l2_modified' set but not used [-Werror=unused-but-set-variable]
/src/qemu/block/qcow2-refcount.c:708:9: error: variable 'l2_size' set but not used [-Werror=unused-but-set-variable]

CC: Kevin Wolf <kwolf@redhat.com>
Signed-off-by: Blue Swirl <blauwirbel@gmail.com>
Signed-off-by: Kevin Wolf <kwolf@redhat.com>
(cherry picked from commit 1869a65385e9d81f490b4203dd070cc49b7749c9)
---
 block/qcow2-refcount.c |    5 +----
 1 files changed, 1 insertions(+), 4 deletions(-)

Signed-off-by: Michal Novotny <minovotn@redhat.com>