QError: Introduce QERR_IO_ERROR
RH-Author: Jeffrey Cody <jcody@redhat.com>
Message-id: <f984e0147ba2f5f1a440da1b3fdaa9b43d0bbfc0.1332249823.git.jcody@redhat.com>
Patchwork-id: 38645
O-Subject: [RHEL6.3 qemu-kvm PATCH v3 18/21] QError: Introduce QERR_IO_ERROR
Bugzilla: 784153
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Markus Armbruster <armbru@redhat.com>

From: Luiz Capitulino <lcapitulino@redhat.com>

Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
(cherry picked from commit 588988736634ad2aa356dafac78f88d1ea68b1a4)
Signed-off-by: Jeff Cody <jcody@redhat.com>
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>