qerror: add qerror_report_err()
RH-Author: Jeffrey Cody <jcody@redhat.com>
Message-id: <28699b93ec0305290cd0f3866b02508971478651.1332249823.git.jcody@redhat.com>
Patchwork-id: 38644
O-Subject: [RHEL6.3 qemu-kvm PATCH v3 16/21] qerror: add qerror_report_err()
Bugzilla: 784153
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Markus Armbruster <armbru@redhat.com>

From: Anthony Liguori <aliguori@us.ibm.com>

This provides a bridge between Error (new error mechanism) and QError (old error
mechanism).  Errors can be propagated whereas QError cannot.

The minor evilness avoids layering violations.  Since QError should go away RSN,
it seems like a reasonable hack.

Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>
Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
(cherry picked from commit 2a82d936a2bda9cb01d05fc91845e82001b78632)

Conflicts:

	qerror.h
Signed-off-by: Jeff Cody <jcody@redhat.com>
---
 qerror.c |   33 +++++++++++++++++++++++++++++++++
 qerror.h |    2 ++
 2 files changed, 35 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>