tools: kvm_stat: Powerpc related fixes
After reverting 60b412dd (removing kvm_stat) we need to backport the kvm_stat fixes.

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1389238
BREW: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=12088436

From: Hemant Kumar <hemant@linux.vnet.ibm.com>

kvm_stat script is failing to execute on powerpc :
 # ./kvm_stat
Traceback (most recent call last):
  File "./kvm_stat", line 825, in <module>
    main()
  File "./kvm_stat", line 813, in main
    providers = get_providers(options)
  File "./kvm_stat", line 778, in get_providers
    providers.append(TracepointProvider())
  File "./kvm_stat", line 416, in __init__
    self.filters = get_filters()
  File "./kvm_stat", line 315, in get_filters
    if ARCH.exit_reasons:
AttributeError: 'ArchPPC' object has no attribute 'exit_reasons'

This is because, its trying to access a non-defined attribute.

Also, the IOCTL number of RESET is incorrect for powerpc. The correct
number has been added.

Signed-off-by: Hemant Kumar <hemant@linux.vnet.ibm.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

This patch is an upstream commit in the kernel repo, but applied
downstream only in the qemu repo.

kvm_stat has moved to the kernel repo since:

    [qemu]  60b412d kvm_stat: Remove
    [linux] f9bc9e6 tools: Add kvm_stat vm monitor script

This patch is a backport of the patch applied to the kernel repo to
the qemu repo:

    [linux] c7d4fb5 tools: kvm_stat: Powerpc related fixes

The original patch was also posted on the qemu-devel ML:

    http://patchwork.ozlabs.org/patch/611965/

Signed-off-by: Laurent Vivier <lvivier@redhat.com>
Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>