error: New error_fatal
Message-id: <1442852135-32495-2-git-send-email-armbru@redhat.com>
Patchwork-id: 67850
O-Subject: [RHEV-7.2 qemu-kvm-rhev PATCH 1/4] error: New error_fatal
Bugzilla: 1232308
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Dr. David Alan Gilbert <dgilbert@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>

Similar to error_abort, but doesn't report where the error was
created, and terminates the process with exit(1) rather than abort().

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Message-Id: <1441983105-26376-2-git-send-email-armbru@redhat.com>
Reviewed-by: Eric Blake <eblake@redhat.com>
Reviewed-by: Peter Crosthwaite <crosthwaite.peter@gmail.com>
(cherry picked from commit a29a37b994ca3c5a1d39fa0e8934f7e0f2cf57ef)
Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>

Conflicts:
	include/qapi/error.h
	util/error.c

Conflicts because we lack "On abort, report where the error was
created" (commit fbf054c..1e9b65b).  Would be nice to have, but
requires the QError purge (commit f006cf7..a0b1a66 plus
prerequisites), and that seems to invasive right now.

Signed-off-by: Markus Armbruster <armbru@redhat.com>