error: New qemu_opts_loc_restore()
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1312812947-8303-5-git-send-email-armbru@redhat.com>
Patchwork-id: 31081
O-Subject: [RHEL6 PATCH qemu-kvm 4/5] error: New qemu_opts_loc_restore()
Bugzilla: 711354
RH-Acked-by: Gerd Hoffmann <kraxel@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Amit Shah <amit.shah@redhat.com>

Needed for decent error locations when complaining about options
outside of qemu_opts_foreach().  That one sets the location
already.

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Signed-off-by: Kevin Wolf <kwolf@redhat.com>
(cherry picked from commit 94ac726842d37b50c7742ecb643bebe2e5d72cd2)
---
 qemu-option.c |    5 +++++
 qemu-option.h |    1 +
 2 files changed, 6 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>